### PR TITLE
Added gradle build system

### LINKED ISSUE #34: [Crash] issue with Survival Inc. mod
**Short Description**
When the game tries to render your body when you are a ghost (feature from Surival Inc.), the game crashes

**To Reproduce**
1. Play with HBM's Nuclear Tech Mod and Survival Inc.
2. Die
3. Press "E" or "F5"

**Crash Report**
https://pastebin.com/PdvPbYG0

**Additional Notes**
HBM's Nuclear Tech Mod version: 1.3.7.1a.
Survival Inc. version: 1.2.0

the developer of Survival Inc. said this:
> EDIT: Okay I had a quick look on the source you have linked (really thanks for that!), but the actual conflicting code seems to be on [Line 1152](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/blob/1.12.2_test/com/hbm/main/ModEventHandlerClient.java#L1152) in method preRenderLiving. They're basically assuming that everything that renders player as EntityLivingBase uses RenderPlayer (see the cast to RenderPlayer on that line). This is assumption may be true for vanilla, but not for anything that replaces the default player renderer (RenderPlayer). Looking at the code, it should behave exactly the same if they had used just RenderLivingBase instead of RenderPlayer (i.e. the RenderPlayer cast is an unnecessary assumption leading to errors like this).

Link to the issue: https://github.com/Enginecrafter77/SurvivalInc/issues/23

### PR DESCRIPTION
**Pull request by Enginecrafter77**
Gradle build system is usually included as part of the repository to avoid unnecessary hassle every time a person needs to compile the mod from source. This step essentially makes setting up the project more streamlined and compilant with the norms.

Also, this PR fixes #34, see https://github.com/Enginecrafter77/Hbm-s-Nuclear-Tech-GIT/commit/c4ec5d426c3f94a69ab88d05914951dfe1b97ce7 for more info.

### CODE REVIEW

**Comment by Drillgon200** [comment]
Alright, couple of issues. I don't know if this matters, but my group is "com.hbm" and archivesBaseName is "hbm" in build.gradle.
The code with specialDeathEffectEntities in ModEventHandlerClient must be done in a regular render event, because it causes any entity to not render (actually I'm not sure if that render removal code does anything at all since the entity should just be removed and netty keeps packet order, but I'm too lazy to fully check it).
I have no idea what git version is or how to use it. When I change my garbage versioning system, I've always just changed the reference in code, build.gradle, and used the right version when creating a release.

**Comment by Enginecrafter77** [comment]
Yeah I didn't really know what I should put into the archivesBaseName; usually it's the name of the mod. But good to know, I will make additional fixup commit on that.

Also, what do you mean by that? At least from what I came to, the code should only run for player entities, so moving it over to preRenderPlayer has the same effect, just that it avoids making assumptions about the renderer and removes the need to check the entity type. Could you please provide some example of issue it might cause?

Gitversion is a little gradle plugin to make your life a little bit easier. It automatically generates the version string for your project. For example, when you have just made a tag with name v1.2.0, then the version built on that tree will be called "hbm-v1.2.0.jar". If you make a commit to that tree, the next version will be "hbm-v1.2.0-1-[commitid].jar". It's really helpful and removes the need to change those things manually, since the only thing you have to do is to make a release here on github and gitversion will take care of the rest.

**Comment by Drillgon200** [comment]
Most of that code does only run for player entities, but the part with specialDeathEffectEntities runs for any entity. Specifically, it's used for the mob gibbing effect I made for the gluon gun. The mob is transformed into a particle for each cube, and this stops the regular one from rendering so the transition to particles is perfect and the mob stops rendering as soon as the particles appear.

Neat.

**Comment by Enginecrafter77** [comment]
Well okay so I will try to reintegrate it as it was, just without the player-bound code.

**Comment by Enginecrafter77** [comment]
Okay so it should be fixed now. When you have time, please review the PR again to see if there are any remaining issues.

**Pull request merged**
