### PR TITLE
Improved dependency management

### PR DESCRIPTION
**Pull request by Enginecrafter77**
By harnessing the power of gradle and maven, dependencies can now be managed much more easily and in a much more elegant manner. Glmath and redstoneflux source files were removed. Both glmath and redstone flux are now declared as dependencies in build.gradle. Redstone Flux is required as a dependency to be present in the mod environment (the mod won't load without it), and glmath is packed in the jar after compilation (much like it is now). The final effect is a little bit faster build time, since all the libraries come pre-compiled.

### CODE REVIEW

**Comment by Drillgon200** [comment]
I don't like the idea of depending on an external RF jar. Can I make that optional?

**Comment by Enginecrafter77** [comment]
Well I think it might be possible to do so using some conditional gradle compiling. But in general, it would be best if it was either that you bundle the code as you used to or just depend on the RF jar (the latter being the more standard way of doing so). 

Alternatively, you may migrate completely to Forge Energy, eliminating the need for redstone flux altogether (but it would be a little more tedious to do so).

But feel free to reject the PR if it does not fit your modding style; ultimately, I did this on a separate branch just because I knew it would be a little more controversial step.

So to conclude, the general advantage are:
* The RF API may be updated independently of your codebase
    * Optionally, the user may provide an alternative RF API implementation, which adds to the overall flexibility of the mod's use case
* The modded environment is more resource friendly (memory-wise), since the RF API code would already be loaded in memory.
* Nearly every modpack includes RF API, so there is no need to worry about users blaming you for it.

The obvious disadvantage is that the user needs to download RF API, but as I already mentioned, they would need to do that either way if they use any tech mod esides HBM NT anyways.

But ultimately, it is your choice.

**Comment by Drillgon200** [comment]
I just don't want to force people to download more files than necessary, it's just annoying to download a mod and start your game only to realize the mod you downloaded has 3 dependencies you need to also download, especially when NTM doesn't even use RF on its own and only uses it to be compatible with other mods anyway. Ideally I'd have it packaged with its own RF API, but use the one in the rf jar if it's present.

**Comment by Enginecrafter77** [comment]
I don't really think it would be possible to somehow "unload" the RF API once it's bundled in your mod. Alternatively, if you want to be dependency-free, you can use the shadowJar task in gradle to bundle the RF API jar in. I don't know if you have tried running the version off my branch, but that's exactly how the glmath library is currently handled.

I still think you should leave it as a required dependency (for reasons I illustrated above); the forge mod dependency system was created just for that. When I was testing the mod in my test environment (obfuscated, aka "how would an average player install the mod"), the only mod besides HBM that was required in the mods directory was the RF API jar, which is really just about 32K in size.

Another possible solution is to make HTM automatically download the RF API jar, which would be a little tricky, but still possible.

So, in the end, I guess you would like to go with the shadowJar solution, aka bundle the RF API into the mod jar, right?

**Comment by Drillgon200** [comment]
Yeah probably. I guess I'll try that when I finish porting some stuff.

**Pull request closed without merging**
